### ISSUE TITLE
httpoison dependency update

### ISSUE THREAD

**Issue by tanweerdev** [codedge-llc/pigeon#107]
httpoison dependency is not up-to date. Current version is 1.0.0

**Comment by hpopp** [comment]
I'll have to check and make sure it doesn't break anything. Ideally we should support both 0.x and 1.0, as it has only been out for a few weeks.

@talklittle

**Comment by talklittle** [comment]
Looks like no substantive changes between HTTPoison 0.13.0 and 1.0.0. One dependency update for httparrot and otherwise only documentation updates. https://github.com/edgurgel/httpoison/compare/v0.13.0...v1.0.0

**Comment by hpopp** [comment]
Works for me, I'll post a release.

**Comment by tanweerdev** [comment]
thanks(it works with newer version I have also tested). Release would be great
