### ISSUE TITLE
Starting APNS connection with certificate string and key failing.

### ISSUE THREAD

**Issue by krlgrgn** [codedge-llc/pigeon#114]
Hi guys, thank you for making a great library. I have a small question about an issue I'm having.

I'm trying to connect to APNS using the full text string of the cert and key. I'm not cutting anything out of the string I'm running: 

`{certificate_str, _exit_code} = System.cmd("openssl", ["pkcs12", "-in", p12_cert, "-passin", "pass:#{cert_password}", "-nokeys", "-nodes"])`

for the cert and

`{key_str, _exit_code} = System.cmd("openssl", ["pkcs12", "-in", p12_cert, "-passin", "pass:#{cert_password}", "-nocerts", "-nodes"])`

for the key.

I then use `Pigeon.APNS.start_connection(cert: certificate_str, key: key_str, mode: :dev)`

to try and start the connection but I get this error:

```
** (EXIT from #PID<0.588.0>) shell process exited with reason: time out
```

However when I pass the file path for the pem files, it works fine.

Am I missing something?
Any help would be apreciated. Let me know if you need any more information.

Thanks

**Comment by hpopp** [comment]
Haven't seen anyone use it like this yet. Usually I bind the whole cert string to an environment variable.

Just to make sure its a typo, you're binding `{certificate_str, _exit_code}` twice in your example?

**Comment by krlgrgn** [comment]
Hi @hpopp. My bad that's a typo. I've fixed the typo.

Those System commands just give me the complete contents of the file. Do I just need the cert string? (i.e. the content between `---- BEGIN CERTIFICATE ----` and `----- END CERTIFICATE -----`)

**Comment by hpopp** [comment]
Pigeon's test suite includes the `---- BEGIN CERTIFICATE ----` and `----- END CERTIFICATE -----` in it's config.

Try running `:public_key.pem_decode/1` on either of your strings and tell me what you get.

**Comment by krlgrgn** [comment]
Hi @hpopp 

It was quite silly on my part. I didn't decrypt my private key properly, and did not extract `MAC verified OK\n` from the output of the os commands.. I tried this:
```
cert = :os.cmd(:"openssl pkcs12 -in #{p12_cert} -passin pass:#{cert_password} -nokeys")
          |> List.to_string
          |> String.replace("MAC verified OK\n", "")

key =  :os.cmd(:"openssl pkcs12 -in #{p12_cert} -passin pass:#{cert_password} -nocerts -nodes | openssl rsa")
           |> List.to_string
           |> String.replace("MAC verified OK\n", "")

Pigeon.APNS.start_connection(cert: cert, key: key, mode: :dev)
```

Thanks for your help and apologies for any inconvenience. I know issue are really the place for something like this.

**Comment by hpopp** [comment]
No worries, someone else will probably find this useful in the future!
