### ISSUE TITLE
How to config multiple apps?

### ISSUE THREAD

**Issue by hopewise** [codedge-llc/pigeon#118]
We have two android apps that we will be sending push notifications to.
The question is how would I add the configuration?

As far as in the docs:

```
config :pigeon, :fcm,
  fcm_default: %{
    key: "key"
  }
```
then, I can send to as:

    Pigeon.FCM.Notification.new("your device registration ID", msg)

but if I set the other app config as:

```
config :pigeon, :fcm,
  fcm_other_app: %{
    key: "key"
  }
```

then, how would I reference it when I send message to??

**Comment by hopewise** [comment]
Thanks

**Comment by simpers** [comment]
Is it possible to dynamically set certificates/secrets per app after deploying? Say that I add a new bundle ID for my iOS app for testing and I have a new certificate along with that. I wouldn't want to reboot my pigeon microservice as it would affect other deployments, possibly. Or do I need to add a new entry to config.exs and redeploy?

If not, how much work would it be to allow this dynamic configuration? We're thinking of deploying a microservice for all of our apps to remove the certificate handling from our APIs so that they all go through this one microservice instead.

**Comment by hpopp** [comment]
Yes they can be dynamically started!

```elixir
{:ok, pid} = Pigeon.APNS.start_connection(cert: System.get_env("APNS_CERTIFICATE"), key: System.get_env("APNS_KEY"), mode: :dev)
Pigeon.APNS.push(notif, to: pid)

Pigeon.APNS.start_connection(cert: System.get_env("APNS_CERTIFICATE"), key: System.get_env("APNS_KEY"), mode: :dev, name: :custom)
Pigeon.APNS.push(notif, to: :custom)
```

**Comment by simpers** [comment]
> Yes they can be dynamically started!
> 
> ```elixir
> config = Pigeon.APNS.Config.new(name: :custom, cert: System.get_env("APNS_CERTIFICATE"), key: System.get_env("APNS_KEY"), mode: :dev)
> {:ok, pid} = Pigeon.start_connection(config)
> 
> Pigeon.APNS.push(notif, to: pid)
> Pigeon.APNS.push(notif, to: :custom)
> ```
> 
> Edit: Fixed input config

Great! So I'd basically have build some sort of mechanism for managing this. Killing and starting workers when certificates change, etc. Thanks for a quick reply 👍

**Comment by simpers** [comment]
> ```elixir
> config = Pigeon.APNS.Config.new(name: :custom, cert: System.get_env("APNS_CERTIFICATE"), key: System.get_env("APNS_KEY"), mode: :dev)
> {:ok, pid} = Pigeon.start_connection(config)
> 
> Pigeon.APNS.push(notif, to: pid)
> Pigeon.APNS.push(notif, to: :custom)
> ```

The equivalent for FCM would thus be:

```elixir
config = Pigeon.FCM.Config.new(name: :custom, key: "my-awesome-server-key", mode: :dev)
{:ok, pid} = Pigeon.start_connection(config)
Pigeon.FCM.push(notification, to: pid)
```

I am trying to test this out in `iex -S mix` to see if I can send a message to my phone using a hardcode registration_id that I have access to for now, just to test things out. I get an error though when trying to start the process:

```elixir
{:error,
 {{:EXIT,
   {:function_clause,
    [
      {Pigeon.Connection, :start_link,
       [
         %Pigeon.FCM.Config{
           key: "grandma's secret sauce",
           name: :tol_android,
           port: 443,
           uri: 'fcm.googleapis.com'
         }
       ], [file: 'lib/pigeon/connection.ex', line: 34]},
      {:supervisor, :do_start_child_i, 3, [file: 'supervisor.erl', line: 379]},
      {:supervisor, :do_start_child, 2, [file: 'supervisor.erl', line: 365]},
      {:supervisor, :handle_start_child, 2, [file: 'supervisor.erl', line: 671]},
      {:supervisor, :handle_call, 3, [file: 'supervisor.erl', line: 420]},
      {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 661]},
      {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 690]},
      {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}
    ]}},
  {:child, :undefined, #Reference<0.682623879.3300917252.80013>,
   {Pigeon.Connection, :start_link,
    [
      %Pigeon.FCM.Config{
        key: "grandma's secret sauce",
        name: :tol_android,
        port: 443,
        uri: 'fcm.googleapis.com'
      }
    ]}, :temporary, 5000, :worker, [Pigeon.Connection]}}}
```

Or are there other steps I need to take before starting this configuration?

**Comment by hpopp** [comment]
I think there might be a regression. `Pigeon.APNS.start_connection/1` and `Pigeon.FCM.start_connection/1` work fine, so use those until I can address.

**Comment by simpers** [comment]
> I think there might be a regression. `Pigeon.APNS.start_connection/1` and `Pigeon.FCM.start_connection/1` work fine, so use those until I can address.

I managed to send my self a test notification using `Pigeon.FCM.start_connection/1` directly instead of Pigeon.start_connection/1.

Apparently I forgot to post this properly so it has been hanging around in my Chrome tab all weekend. Just confirming that it worked.

**Comment by shawarmaz** [comment]
How is this done in v2? 

Preferably statically, for 2 different apps, no dynamic requirements.
