### ISSUE TITLE
My firewall drops connection after 30 min idle time

### ISSUE THREAD

**Issue by arkadiyk** [codedge-llc/pigeon#12]
I have implemented a periodic ping to keep the connection alive: https://github.com/arkadiyk/pigeon/commit/83919469d8b9be4753143e493c039d5a78077ccd

Does it make sense to solve the problem this way? If it does I can make the timeout configurable and make a PR..

`apns4erl` solved this problem in different way: https://github.com/inaka/apns4erl/pull/54

**Comment by hpopp** [comment]
I thought about adding something like this a while back but haven't yet gotten around to it. If it's working for you, let's implement it. Apple prefers keeping the connections alive as long as possible, specifically noting use of the HTTP/2 `PING` frame for health checks. Ultimately this solution will play out nicer than apns4erl, as long as I ensure the connection fail-safes are rock-solid before `v1.0`.

No need to make the timeout configurable. One of the goals of pigeon is to be *dead simple* to use, and that includes having as few config keys as possible. Connection pings aren't something a dev should have to worry about.

Make the timeout 10 mins, refactor it into an `@ping` declaration near the top of the module, and it should be good to go.

**Comment by hpopp** [comment]
These changes were obsoleted in the `v0.8` migration to chatterbox. Might be worth double checking to make sure everything still works. I left a connection open for over an hour and seemed to have no problem.
