### ISSUE TITLE
Set time to live

### ISSUE THREAD

**Issue by tuomohopia** [codedge-llc/pigeon#121]
I'm not sure if I'm missing something here but I don't see a way to set the time-to-live for push notifs. Being able to set one is crucial in my app so I desperately need it.

Could it just be added to the `%Pigeon.FCM.Notification{}` struct?

**Comment by hpopp** [comment]
I'll need to add it to the struct. Might as well add the other missing ones too (except the iOS-related ones).

I don't *think* it will be API-breaking, so I could have a patch out shortly.

**Comment by hpopp** [comment]
Keys added in #122 

@talklittle is there anything missing for ADM notifications?

**Comment by talklittle** [comment]
Let me check. `time_to_live`, `collapse_key`, `restricted_package_name` right?

**Comment by hpopp** [comment]
Yup, `dry_run` too

**Comment by talklittle** [comment]
ADM has `expires_after` which corresponds to TTL and mentioned in Pigeon Readme already https://github.com/codedge-llc/pigeon/blob/9721449c524e72d625b7d9cd30f740845ddd2ec6/README.md#amazon-android-adm

Didn't see anything in [ADM docs](https://developer.amazon.com/docs/adm/send-message.html#request-format) about other keys, so probably can ignore for ADM.

**Comment by hpopp** [comment]
Awesome, `v1.2.1` is out.

**Comment by hpopp** [comment]
Thanks for raising the issue!

I remembered after publishing that it was in fact possible to add the keys manually, but it was hackish and unintuitive. I'm wondering how we got to almost 90K downloads without more complaints about this.
