### ISSUE TITLE
Can I use FCM for iOS?

### ISSUE THREAD

**Issue by Taillook** [codedge-llc/pigeon#126]
**Is your feature request related to a problem? Please describe.**
I'm developing a mobile app for iOS and Android.
I want to Integration iOS and Android for notification function.
Right now, I use iOS and Android different functions for notification.
So I want to use FCM for iOS.

**Describe the solution you'd like**
Can I use the current Pigeon.FCM.Notification on iOS?

**Comment by hpopp** [comment]
It should work, though I've never tried. You'll need to manually set the notification keys defined in https://firebase.google.com/docs/cloud-messaging/http-server-ref

**Comment by Taillook** [comment]
Thanks your reply.
I'll try it.

**Comment by krystofbe** [comment]
@Taillook: Did you manage to get it to work? Can you post an example?

**Comment by larquin** [comment]
I'm also looking for some guidance on this, and curious if anyone has gotten this to work.

**Comment by hpopp** [comment]
I think I might have to create a sample project myself to see if this is supported. I've never needed it in production.

That said, `Pigeon.FCM.Notification.put_notification/2` is going to be your friend for setting the iOS keys. Worst case, you can update the `:payload` struct key directly to match FCM's API.

**Comment by hpopp** [comment]
Verified that yes, you can send FCM notifications to iOS. I followed [FCM's guide](https://firebase.google.com/docs/ios/setup) for it and it seemed to work out of the box.

**Comment by carlosgrell** [comment]
I'm trying the same thing but I keep getting a "malformed_json" status when calling the .push method. Has anyone faced this issue?

**Comment by halostatue** [comment]
We were experiencing a similar problem; it turned out that our FCM key had an additional `"\n"` at the end of the key which was being transmitted and causing failures.
