### ISSUE TITLE
Add way to integrate into existing supervision tree

### ISSUE THREAD

**Issue by nsweeting** [codedge-llc/pigeon#128]
Currently, there is no easy way to integrate pigeon with your own apps supervision tree. This can be frustrating if you're wanting to do any kind of runtime config, as you have to start pigeon yourself vs adding it to your supervision tree.
 
It would be nice to see all code currently in the `Pigeon` module moved to a `Pigeon.Supervisor` module that uses the `Supervisor` behaviour. Or potentially add `child_spec/1` and  `start_link/1` functions to the main `Pigeon` module.

**Comment by hpopp** [comment]
You'd want to use `Pigeon.Worker` for APNS/FCM and `Pigeon.ADM.Worker` for ADM.

```elixir
  def start(_type, _args) do
    children = [
      {Pigeon.Worker,
       %Pigeon.FCM.Config{
         name: :fcm_custom,
         key: "your_fcm_key"
       }}
    ]

    opts = [strategy: :one_for_one, name: YourApp.Supervsior]
    Supervisor.start_link(children, opts)
  end
```

```elixir
iex> n = Pigeon.FCM.Notification.new("regid", %{}, %{"message" => "something"})
iex> Pigeon.FCM.push(n, to: :fcm_custom)
```

I realize now this is completely undocumented in the official docs 😅.  `Pigeon.Worker` takes any struct that implements the `Pigeon.Configurable` protocol, but this is currently limited to only APNS and FCM configs. ADM servers don't support HTTP/2 yet, so it still uses its own `ADM.Worker`. As long as the `:name` key is set in any of the configs, you can push to the worker regardless of where it's supervised.

I'll look into adding some guides for this.
