### ISSUE TITLE
put_sound break the contract on Dialyxir

### ISSUE THREAD

**Issue by laibulle** [codedge-llc/pigeon#135]
### Environment

* Elixir & Erlang/OTP versions (`Elixir 1.7.3`): 
* Operating system: `OSX Mojave `
* Dialyxir version: `1.0.0-rc.4`

### Current behavior

```
Pigeon.APNS.Notification.put_sound(%Pigeon.APNS.Notification{}, "default")
```

return the following error with Dialyxir 1.0

```
The call:
Pigeon.APNS.Notification.put_sound(
  %Pigeon.APNS.Notification{
    :device_token => _,
    :expiration => nil,
    :id => nil,
    :payload => %{<<_::24>> => %{<<_::40>> => _}},
    :topic => _
  },
  <<_::56>>
)

breaks the contract
(t(), String.t()) :: t()
____________________________
```

### Expected behavior

Dialyxir should not return any error

**Comment by hpopp** [comment]
Running the exact same environment but I haven't been able to reproduce yet. What version of pigeon are you using?

**Comment by laibulle** [comment]
I am using the version `1.0.0`
