### ISSUE TITLE
Will this work with 10M subscribers?

### ISSUE THREAD

**Issue by 9mm** [codedge-llc/pigeon#136]
I'm still learning how all these pieces fit together, but currently I'm using FCM to generate the token.

As far as the 'sending' piece, I'm using the legacy API.. but the problem is I need to send 10M notifications * 4 every day, and it CANT be a broadcast notification (they need to be personalized)

I can't really use the legacy API (I dont think) because thats 40M API requests a day which I would imagine would time-out or be rate limited.

Does this library actually *send* to the clients or does it just hit google legacy endpoint? Do you know any way I could do this so I can send the messages myself on a big 32 GB memory server?

**Comment by hpopp** [comment]
It hits the legacy endpoint, but AFAIK you shouldn't hit limits with that kind of volume. @talklittle might have something to say about this.

**Comment by 9mm** [comment]
I researched everywhere for API limits, quotas, etc. It's nowhere to be found. A quick multithreaded test results in some connections timing out so obviously some rate limit or max connection limit is applying, I just don't know what it is. It's frustrating that Google doesn't specifically outline the rules.

I am thinking of using XMPP and just doing the 100 connection limit, as outlined in the discord article about sending a million pushes a minute.

**Comment by hpopp** [comment]
Are you using the `on_response` callback option for async pushes? I recommend it for anything high-volume. Synchronous pushes will almost always timeout if you're sending greater than a few thousand.

**Comment by 9mm** [comment]
I'm not actually using pidgeon yet, I just wanted to see if it would be able to handle it before I start adding it. Thanks for your help guys!

**Comment by flyrboy96** [comment]
Along these lines, is it possible to limit the number of concurrent pushes for the `on_response` async option? We send a lot of batched notifications and are timing out currently so we need the async ability, but don't have a huge server so I want to make sure it won't block incoming API requests while pushing the notifications.

**Comment by hpopp** [comment]
Max concurrency for APNS and FCM is hard limited to 250 and 1000 notifications, respectively. If you want something else, I would dump synchronous pushes into a `Task.async_stream/3` with `:max_concurrency` set.

**Comment by flyrboy96** [comment]
Thanks for the advice + time!

**Comment by hpopp** [comment]
I think this thread warrants me writing a guide for both high volume pushes and custom control flow. I'll add it to my list.
