### ISSUE TITLE
New release on hex.pm

### ISSUE THREAD

**Issue by victorolinasc** [codedge-llc/pigeon#144]
**Is your feature request related to a problem? Please describe.**

First of all, thanks for this open source library! Great work!

I'm one of the maintainers of Joken and came here to see if help was needed to upgrade to 2.0. It seems master is already at it, so I was wondering if there is anything blocking you on a 1.3.0 release. I am sorry for the breaking change on Joken but it was needed on our side. 

I can depend on master if the release is planned to be pushed soon. 

**Describe the solution you'd like**

Make 1.3.0 available on hex.pm :)

Once again, thanks for your work. If there is anything from Joken's side you'd like help with please just say it and I'll be glad to help.

**Comment by hpopp** [comment]
No worries, nothing is blocking! I haven't finalized release yet because I've been crunching a couple deadlines for work 😅 

It's on my list to do a final check this week and it'll be up.

**Comment by hpopp** [comment]
Release is up!
