### ISSUE TITLE
APNS worker times out

### ISSUE THREAD

**Issue by walkr** [codedge-llc/pigeon#157]
### Environment

   - Elixir 1.9.2 (compiled with Erlang/OTP 21) 
   - Erlang/OTP 22 [erts-10.5.3]
   - Ubuntu 18.04.3 LTS

### Issue

Hello,

I'm getting the following timeout triggered when pushing Apple notifications.

https://github.com/codedge-llc/pigeon/blob/92e7e5edea43d5f1ce8d38d2eae54d308032975b/lib/pigeon/apns.ex#L168

Pigeon works on my Apple machine `Elixir 1.9.2 (compiled with Erlang/OTP 22) + Erlang/OTP 22 [erts-10.5.2]`, but fails on the server, where I use Ubuntu `Elixir 1.9.2 (compiled with Erlang/OTP 21)  + Erlang/OTP 22 [erts-10.5.3]`

Any suggestions? 

I'm also seeing pigeon not tested on OTP 22. Any issues to be aware of?

Thank you!

**Comment by walkr** [comment]
If you're referring to allowing incoming connections on ports 443 and 2197, why would that be necessary, pigeon is just the client?

I tested connecting to Apple's push servers with telnet, and both ports are reachable.

**Comment by hpopp** [comment]
I realized post-merge that #158 breaks APNS configs that use full-text certs & keys instead of file paths. I'll have to rework a bit before release but I agree that configs should raise if a file is not found.

**Comment by edisonywh** [comment]
I'm having this issue as well, my requests just keeps timing out and I have zero idea why. It doesn't look you've released a new version on Hex yet so #158 should not impact, but it still times out..

**Comment by hpopp** [comment]
Closed with #161
