### ISSUE TITLE
Provide notification payload on Android

### ISSUE THREAD

**Issue by Lida** [codedge-llc/pigeon#16]
Currently, Pigeon.GCM.Notification only has a data field. Please provide ability to pass in a notification payload according to [GCM reference](https://developers.google.com/cloud-messaging/concept-options#notifications_and_data_messages)

**Comment by hpopp** [comment]
Making a note here for the `v0.8` release. `Pigeon.GCM.Notification.new/2` should be rewritten to take a message string as it's first parameter, which will then get encoded as `%{ message: "message" }` on the `data` key. `put_notification` and `put_data` functions will then be added to explicitly set the maps on the JSON payload.
