### ISSUE TITLE
Typespec for Pigeon.APNS.Notification is incomplete

### ISSUE THREAD

**Issue by sevenseacat** [codedge-llc/pigeon#168]
Referring to the `payload` field documented here:
https://github.com/codedge-llc/pigeon/blob/master/lib/pigeon/apns/notification.ex#L42

It doesn't match the documentation here:
https://github.com/codedge-llc/pigeon/blob/master/lib/pigeon/apns/notification.ex#L278

(or any of the examples in the file, that have `aps` as a map)

This raises errors when testing with a tool like Hammox:

```
** (Hammox.TypeMatchError)
1st argument value %Pigeon.APNS.Notification{collapse_id: nil, device_token: "1234", expiration: nil, id: nil, payload: %{"aps" => %{"alert" => "AC Fail", "sound" => "new_alarm.mp3"}, "type" => "alarm_created"}, priority: nil, push_type: "alert", response: nil, topic: "com.company.appname"} does not match 1st parameter's type Pigeon.APNS.Notification.t().
  Map value %{"aps" => %{"alert" => "AC Fail", "sound" => "new_alarm.mp3"}, "type" => "alarm_created"} for key :payload does not match map value type %{required(String.t()) => String.t()}.
    Map value %{"alert" => "AC Fail", "sound" => "new_alarm.mp3"} for key "aps" does not match map value type String.t().
      Value %{"alert" => "AC Fail", "sound" => "new_alarm.mp3"} does not match type <<_::_*8>>.
```

**Comment by hpopp** [comment]
I have an open branch at #170 that fixes all outstanding dialyzer issues. I made the requested change that should fix your issue, but unfortunately dialyzer wouldn't catch it and I don't personally use Hammox for anything.

Give it a try and see if it works for you?

**Comment by hpopp** [comment]
To make it easier to find, here's the updated relevant typespec:

https://github.com/codedge-llc/pigeon/blob/678d1c1528d6cf4bd8a7805ca72f7176be95bbee/lib/pigeon/apns/notification.ex#L42

**Comment by sevenseacat** [comment]
I don't think that'll fix the issue - because some of the values in the map can also be scalars. I think it would have to be `any()`?

(Sorry I'm not too well versed in dialyzer, it just came up)

**Comment by hpopp** [comment]
`term` and `any` are the same same under the hood. If the overall structure works for you I'll go ahead and merge. It's about as correct as I can make it given Pigeon's API.

**Comment by sevenseacat** [comment]
I mean some of the values in the `payload` map are scalars, they're not all maps. So I think it would have to be `payload: %{String.t() => term}` ?

If that change makes sense and you're okay with that, then please do go ahead and merge!

**Comment by hpopp** [comment]
No, you're right. I misremembered how I wrote the notification functions. For some reason I was under the impression that `put_custom` also wrapped values under the `"aps"` key, but I see it right there in my own docs. 😅

Cool, I'll make the change and merge. Thanks for your help!
