### ISSUE TITLE
Support the FCM HTTP V1 

### ISSUE THREAD

**Issue by msmykowski** [codedge-llc/pigeon#169]
Pigeon currently uses the legacy FCM. We would like to upgrade to the new FCM api, but Pigeon currently does not support it.

https://firebase.google.com/docs/cloud-messaging/migrate-v1

**Comment by hpopp** [comment]
This has been on my roadmap for a while, likely for a Pigeon `v2` release. I need to properly plan through API changes and see if there's any potential issues.

**Comment by tmpduarte** [comment]
@hpopp are there any ETA for this? Is there anything I can help with (I will only have time after mid september 😢 )?

**Comment by hpopp** [comment]
Heh, I've been absolutely swamped with deadlines over the past few weeks. My plan is to pick it back up around mid september again!

**Comment by hpopp** [comment]
[Support for FCM v1 has now been merged to master.](https://github.com/codedge-llc/pigeon/issues/171#issuecomment-841734939) The only thing left is testing and polish. Any feedback on design choices would be much appreciated.
