### ISSUE TITLE
Apns documentation

### ISSUE THREAD

**Issue by long-tran** [codedge-llc/pigeon#17]
I think the documentation should be changed from:
```
config :pigeon, 
  apns_mode: :dev,
  apns_cert: "cert.pem",
  apns_key: "key_unencrypted.pem"
  apns_2197: true (optional)
```
To 

```
config :pigeon, 
  apns_mode: :dev,
  apns_certfile: "cert.pem",
  apns_keyfile: "key_unencrypted.pem"
  apns_2197: true (optional)
```

**Comment by hpopp** [comment]
`cert` and `key` are fairly standard for configuration files. I prefer them abbreviated as they are because of the `apns_` prefix.

However, I'm not opposed to the idea of scoping it to an `:apns` key to make everything more descriptive. Something like:
```elixir
config :pigeon, :apns,
    mode: :dev,
    certificate: "cert.pem",
    private_key: "key_unencrypted.pem"
    use_2197: true
```
