### ISSUE TITLE
apns voip notification errors with 'apns-push-type' invalid

### ISSUE THREAD

**Issue by denniswon** [codedge-llc/pigeon#193]
when I use apn-voip push token registered from ios device, the apns notification push fails with the error `apns-push-type` invalid. According to https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns, it seems that I need to set `apns-push-type` to `voip` not `alert`.
How do I set apns-push-type to the pigeon apns notification?

**Comment by hpopp** [comment]
Pigeon has a `:push_type` attribute that you can set on the [APNS.Notification struct](https://hexdocs.pm/pigeon/Pigeon.APNS.Notification.html#t:t/0).

There aren't any helper functions to set this like the other keys, but perhaps I will consider adding one.

**Comment by denniswon** [comment]
Thanks! @hpopp !
