### ISSUE TITLE
support httpoison 2.0

### ISSUE THREAD

**Issue by anmlnath** [codedge-llc/pigeon#234]
This might just be a matter of loosening the requirements in mix.exs?

> Because pigeon >= 1.1.5 depends on httpoison ~> 0.7 or ~> 1.0 and your app depends on httpoison ~> 2.0, pigeon >= 1.1.5 is forbidden. So, because your app depends on pigeon ~> 1.5, version solving failed.

**Comment by anmlnath** [comment]
I think this is an issue still in the rc based on this line `{:httpoison, "~> 0.7 or ~> 1.0"},` on the main branch

**Comment by hpopp** [comment]
Fixed with #236. I'll be holding off posting a new RC but you can safely override in the meantime.

**Comment by anmlnath** [comment]
Thanks!
