### ISSUE TITLE
Firebase Cloud Messaging: FCM replaces GCM

### ISSUE THREAD

**Issue by nathany** [codedge-llc/pigeon#24]
https://firebase.google.com/docs/cloud-messaging/

I'm not sure if there is a difference from the server -- maybe just a matter of documentation?

**Comment by hpopp** [comment]
Thanks for the heads up. Looks like [the protocol won't change](https://developers.google.com/cloud-messaging/faq) and the [old GCM endpoint will still deliver to FCM](https://developers.google.com/cloud-messaging/android/android-migrate-fcm).

I'll run some tests to see if FCM servers can deliver to GCM clients. If so I'd like to make it the default endpoint in the next release. If I had to guess, HTTP/2 support will come to FCM eventually, so it'd make sense to adopt it now.

**Comment by hpopp** [comment]
Looks like FCM does indeed push to old GCM listeners.

**Comment by chris** [comment]
Nice, cool to see you staying up to date and tracking this. Makes it appealing to use Pigeon as notification solution!
