### ISSUE TITLE
Update "Generating Your Certificate and Key .pem" docs

### ISSUE THREAD

**Issue by shawarmaz** [codedge-llc/pigeon#244]
https://hexdocs.pm/pigeon/2.0.0-rc.1/Pigeon.APNS.html#module-generating-your-certificate-and-key-pem

The `openssl` commands no longer work on OpenSSL 3 (which is part of the stock setup in macOS now it seems?).

Specifically RC2-40-CBC is no longer supported (and using `-legacy` option produces invalid results)

This isn't related to the lib per se, but since there are instructions, I think they should be updated, or footnoted at least. 

For those on macOS, I got it working using previous OpenSSL version by prefixing all the commands to use the OpenSSL 1 executable e.g.

```bash
/opt/homebrew/cellar/openssl@1.1/1.1.1u/bin/openssl pkcs12 -clcerts -nokeys -out cert.pem -in cert.p12
```

**Comment by hpopp** [comment]
Turns out you can still use the `-legacy` option if you handle the appropriate PEM decode case. See #248. This will go out with the next RC.
