### ISSUE TITLE
GCM not showing notification unless app is open

### ISSUE THREAD

**Issue by nathany** [codedge-llc/pigeon#25]
Using the example in the Pigeon README we found that GCM was not showing the notification. It took a while to figure out that the app had to be open.

If the notification contains an alert in a data element it does show the notification on the Nexus device we're testing with.

`"data":{"alert":"your alert"}`

**Comment by tylerhc** [comment]
I was under the impression that push notifications for android apps could only be received when the application was either alive or in the background. Assuming you've implemented using broadcast receivers, the application shouldn't have to be in the foreground to receive the pushes. I'm pulling some of this from experience and this stackoverflow post I read a year ago.

http://stackoverflow.com/questions/24313539/push-notifications-when-app-is-closed

**Comment by nathany** [comment]
I didn't write the Android app that I'm sending pushes too, nor do I have the source code. Maybe it's an issue specific to the Android app I'm testing.
