### ISSUE TITLE
Cannot restart phoenix 

### ISSUE THREAD

**Issue by Douvi** [codedge-llc/pigeon#28]
Sorry to open this issue again, but I got the same error when I try to start a second time the server.

here my conf:
```
config :pigeon,
  apns_mode: :dev,
  apns_cert: {:panda_phoenix, "cert/cert.pem"},
  apns_key: {:panda_phoenix, "cert/key.pem"},
  apns_2197: true

def application do
    [...
     applications:[..., :pigeon]]
  end

defp deps do
    [...
     {:pigeon, "~> 0.9.0"},
     {:chatterbox, "~> 0.3.0-15-g401cef6", github: "joedevivo/chatterbox"},
    ...]
  end
```

I did not succeed to user "0.3.0"

Steps:
1 - `mix deps.clean --all`
2 - `mix deps.get`
3 - `mix phoenix.server` "Ok the server work perfectly and I can send push on iOS"
4 - `control c` to kill the server
5 - `mix phoenix.server` I got the error below

```
** (Mix) Could not start application pigeon: Pigeon.start(:normal, []) returned an error: shutdown: failed to start child: :apns_worker
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, :eaddrinuse}
            src/h2_connection.erl:148: :h2_connection.init/1
            (stdlib) gen_fsm.erl:325: :gen_fsm.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

@hpopp, the flag have set to true and the same issue

@nathany, when I run `ps aux | grep phoenix`, After kill my phoenix server I still have a service phoenix running, I guess:
```
55315 ??         0:01.96 /usr/local/Cellar/erlang/19.0.2/lib/erlang/erts-8.0.2/bin/beam.smp -- -root /usr/local/Cellar/erlang/19.0.2/lib/erlang -progname erl -- -home ......... /Users/douvi/Documents/my_app .......
```

I found a solution I need to kill my service erlang to start again my server...

```
kill -9 55315
```

**Comment by Douvi** [comment]
I found a solution I need to kill my service erlang to start again my server...

**Comment by hpopp** [comment]
Alternatively, remove `apns_2197: true` from your config to use the default 443. I've noticed that chatterbox wants to hold onto non-standard SSL ports even after the server quits.

Ideally you should only use 2197 if 443 is blocked for some reason, but this isn't reflected very well in the README.

**Comment by Douvi** [comment]
Prefect I change the `apns_2197: false` and it's working :)
Thanks
