### ISSUE TITLE
[API] Blocking to handle and report responses

### ISSUE THREAD

**Issue by nathany** [codedge-llc/pigeon#29]
I have a challenge that I'm not sure how to address with the current callback-based API for handling responses.

It works well enough for deleting bad device tokens / registration ids from the database, but I'm not sure how to collect the responses to return a success or failure.

Right now I have a web API that will send notifications to one-or-more devices for a single user. I'd like to be able to launch all the notifications (Android or iOS) for that user, then collect all the responses, and decide what to return back to the API.

Any thoughts on how to accomplish this?

**Comment by hpopp** [comment]
So you want to catch all the async responses and only do something once they're all received? Not sure if it'd be overkill, but it sounds like a use case for a GenServer.

**Comment by nathany** [comment]
I'll take a closer look at `GenServer`. What's not clear to me is if I can wrap the current mechanism of callback functions with something else, or if I may still end up missing callbacks sent after the HTTP request finishes.

**Comment by hpopp** [comment]
I would think something like:

```elixir
Pigeon.APNS.push(n, fn(x) ->
  case x do
    {:ok, notification} ->
      GenServer.cast(worker_pid, {:push, :apns, notification})
    {:error, _reason, notification} ->
      GenServer.cast(worker_pid, {:push, :apns, notification})
  end
end)
```
And then in your GenServer
```elixir
def handle_cast({:push, :apns, notification}, state) do
  inc_count = state[:count] + 1
  cond do
    inc_count == state[:total] ->
      # do the thing when all responses are collected
      GenServer.cast(self, :stop)
      { :noreply, state }
    true ->
      { :noreply, %{state | count: inc_count} }
  end
end

```

**Comment by nathany** [comment]
Thanks for providing an example. The "do the thing when all responses are collected" is return a response to a web API -- indicating whether the notifications were sent successfully or not. 

What I'm still not clear on is how to block that request while waiting for all notifications to send -- but I'm reading through the Elixir Guides for OTP to try to understand this better.

**Comment by nathany** [comment]
For GCM, I'm a bit worried about this? 
> This function will get called on each registration ID assuming some of them were successful.

What happens if I send the same notification to multiple devices and they all fail?

--

@michalmuskala recommended send/receive for to make an async call synchronous, eg. `parent = self(); callback  = fn x -> do_stuff(x); send parent, :done end`  and @benwilson512 mentioned `Enum.map(Task.async) |> Task.yield_many` but I don't think that will work here.

I expect my use case is fairly common. I'm sending a single notification to all devices belonging to a single user and reporting whether it was successful or not.

So far my plan is to split the users devices between iOS and Android and build the equivalent notification for each. For GCM, I can send the notification to all Android devices via Pigeon's API, and for APNS I can write a wrapper to send the notification to all iOS devices via the one-at-a-time API.

I intend to make both of those multi-device push APIs synchronous to the caller, reporting back a list of errors or `:ok`. I can then use Task.async/await to launch the iOS and Android notifications simultaneously and wait for both to complete, mashing together the two responses to give a single :ok or list of errors response.

I will probably continue using a callback to handle individual notification errors, but only for bad_token and update_token, with the former being generalized for both Android and iOS. That's something I already have:

```
  def push_notification(device, n) do
    on_response = fn(response) ->
      case response do
      {:bad_push_token, _token} ->
        Repo.delete(device)
      {:update_push_token, _token, new_push_token} ->
        Repo.update(Ecto.Changeset.change(device, push_token: new_push_token))
      end
    end

    PushService.push(n, on_response)
  end
```

Does that sound reasonable? Are there any plans for Pigeon that might make this easier? Such as an API to send a notification to multiple iOS devices -- or synchronous APIs that allow the caller to do the async part.

**Comment by hpopp** [comment]
I can see how that line would be confusing in the README. If some of the pushes are successful when sent as a list of reg IDs, it implies by default there was not a server error that would invalidate the whole batch (e.g. bad GCM key in the config). Thus, the function will get called on each reg ID individually as either an `:ok` or `:error` tuple.

I will add in synchronous pushes once I'm happy with the new poolboy implementation, which should be finished relatively soon. Currently, synchronous pushing in series would be _slow_.

I'll likely add a bulk notification API, though the `APNS.Notification` struct will never have more than one device token. The idea of a "notification" differs slightly from GCM. The only reason GCM can have several reg IDs in a notification is because google allows up to 1000 reg IDs per HTTP request (something I've seriously considered reworking in pigeon-- it adds unwanted mental complexity). 

The bulk API will probably just return a list of response tuples, one for each notification sent. This should be easy enough to iterate over for any additional work.

**Comment by nathany** [comment]
Hi Henry. The GCM bulk notification feature with a limit of 1000 certainly complicates things. An implementation detail that would be nice to hide -- in a batch notification API.

I don't actually want to send-a-notification, wait, send-a-notification, wait... that would be slow. What I'm wanting to do is have a synchronous API that returns a response -- to get away from callbacks. Then the calling code can use `Task.async`/`Task.yield_many` to launch the notifications concurrently, while collecting all the responses before continuing.

I like the idea of having a bulk notification API return `:ok` if everything sent or `:error, [list of errors]` if any errors occurred (not containing :ok for the notifications that succeeded).

**Comment by nathany** [comment]
For now I'm just going to wrap a synchronous API around Pigeon like this:

```elixir
def push(n, carrier \\ MyApp.Push.Pigeon) do
  # make Pigeon's async API behave synchronously
  parent = self
  on_response = fn(response) ->
    send(parent, {:done, response})
  end
  :ok = carrier.push(n, on_response)

  receive do
    {:done, response} -> response
  end
end
```

Thanks for your help.

**Comment by nathany** [comment]
That code made the API synchronous and got rid of the node.js style call back (though I only use the single device token at a time for GCM, otherwise the callback may fire multiple times).

Then I use `Task.async` and `Task.yield_many` to make the work asynchronous while still gathering all the errors.

```elixir
defp send_notifications(user, build, data) do
  parent = self
  tasks = for device <- user.devices do
    n = if device.push_token, do: build.(device, data)
    Task.async(fn -> push_notification(device, n, parent) end)
  end

  tasks_with_results = Task.yield_many(tasks, @notification_timeout)
  results = Enum.map(tasks_with_results, fn {task, res} ->
    res || Task.shutdown(task, :brutal_kill)
  end)
  errors = for {:ok, {:error, error, device}} <- results do
    {error, device}
  end
  if length(errors) == 0 do
    :ok
  else
    {:error, errors}
  end
end
```

The need to `build` a notification each time is a bit unfortunate. I would rather that the `push` API took a `device_token` or `registration_id` independent of the notification so the same notification could be sent multiple times. It would clean up the code a bit.

```elixir
defp push_notification(device, n, parent) do
  # NOTE: [caller: parent] is for testing in the SQL sandbox to avoid DBConnection.OwnershipError.
  case Push.push(n, @carrier) do
  {:ok, :update_push_token, _token, new_push_token} ->
    Repo.update!(Ecto.Changeset.change(device, push_token: new_push_token), [caller: parent])
    :ok
  {:ok, _n} ->
    :ok
  {:error, :bad_push_token, _token} ->
    Repo.delete!(device, [caller: parent])
    {:error, :bad_push_token, device}
  {:error, error} ->
    {:error, error, device}
  end
end
```

Just FYI.

**Comment by hpopp** [comment]
Was about to tag you in another issue, I implemented bulk & sync pushing with https://github.com/codedge-llc/pigeon/commit/c9619755e1e2284a87bc6b95e86eca0cc9f8bcc1 on the `multiconn` branch. Looks like your approach is fairly similar to the one I took.

**Comment by nathany** [comment]
Nice. I like the idea of grouping the errors in a map like you did.

Btw, you might find this little nugget interesting, as I'm attempting to generalize things for GCM/APNS:

```
def push(%Pigeon.APNS.Notification{} = n, on_response) do
  Pigeon.APNS.push(n, on_response)
end

def push(%Pigeon.GCM.Notification{} = n, on_response) do
  Pigeon.GCM.push(n, on_response)
end
```
