### ISSUE TITLE
Pigeon compatible with Pushkit iOS 8 - VoIP

### ISSUE THREAD

**Issue by Douvi** [codedge-llc/pigeon#30]
Apple introduce for iOS 8.0 push notification with action in background in VoIP.

I would like to know if the lib pigeon in compatible with this feature. You can see below a Git with a full explication of the backend (C#) and iOS app.

[Pushkit-tutorial](https://github.com/sinch/ios-pushkit-tutorial)
[Apple-doc](https://developer.apple.com/reference/pushkit)

Thanks

**Comment by Douvi** [comment]
OK GOODDDDDD NEWSSS :DDD - IT'S WORKING!!!!!. But there is a little modification to do, to make it work about the .pem file.

I check this [tutorial](http://stackoverflow.com/a/28562124/524559)

basically, you just need to encore your `voip_services.cer` (dowloaded from apple developer) and `voip_services.p12` (generated by your keychain)

1) download your `voip_services.cer` from Apple Developer
2) add `voip_services.cer` into keychain
3) Export`voip_services.cer` in .p12 - right click on the file `VoIP Service:<bundle_of_your_app>` and click Export `voip_services.p12`.
4) run `openssl x509 -in voip_services.cer -inform der -out cert.pem`
5) run `openssl pkcs12 -nocerts -out key.pem -in voip_services.p12`
6) to remove the password run `openssl rsa -in key.pem -out key_unencrypted.pem`
7) add `key_unencrypted.pem` and `cert.pem` into you project at `/private/cert_voip/`
8) into `config.exs` you will set you file like this
```
config :pigeon,
  apns_mode: :dev,
  apns_cert: {:my_project, "cert_voip/cert.pem"},
  apns_key: {:my_project, "cert_voip/key.pem"},
  apns_2197: false
```

DONE :D you can run your server and send Push VoIP

Thanks the team for you amazing job...

**Comment by hpopp** [comment]
Glad everything is working for you!
