### ISSUE TITLE
SSL certificate unknown.

### ISSUE THREAD

**Issue by VJ-OK** [codedge-llc/pigeon#33]
({application_start_failure,pigeon,{{shutdown,{failed_to_start_child,apns_worker,{tls_alert,"certificate unknown"}}},{'Elixir.Pigeon',start,[normal,[]]}

**Comment by i-m-v-j** [comment]
it is working for dev, but not in prod.

**Comment by i-m-v-j** [comment]
its working now.

**Comment by progsmile** [comment]
@hpopp Should we have ssl cert on website?

**Comment by hpopp** [comment]
For pigeon or your outward facing site?

**Comment by progsmile** [comment]
I mean ssl for https on api server
So, facing site

**Comment by hpopp** [comment]
That's best to have anyway, but doesn't impact pigeon. APNS requires it's own valid developer cert and key to open a connection to their servers, which can be obtained from the apple developer dashboard.

**Comment by progsmile** [comment]
@hpopp Thank you!
