### ISSUE TITLE
GCM multiple token request.

### ISSUE THREAD

**Issue by VJ-OK** [codedge-llc/pigeon#35]
hello, when i tried doing multiple gcm requests with 
`Pigeon.GCM.Notification.new([android_tokens], msg)`

it threw below error.

`10:55:30.291 [error] Task #PID<0.425.0> started from #PID<0.424.0> terminating
** (ArgumentError) argument error
    :erlang.binary_to_existing_atom("not_registered", :utf8)
    (pigeon) lib/pigeon/gcm.ex:134: Pigeon.GCM.parse_result/1
    (pigeon) lib/pigeon/gcm.ex:111: Pigeon.GCM.process_callback/3
    (pigeon) lib/pigeon/gcm.ex:107: anonymous fn/4 in Pigeon.GCM.handle_200_status/3
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (pigeon) lib/pigeon/gcm.ex:107: Pigeon.GCM.handle_200_status/3
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
Function: #Function<6.133904638/0 in Pigeon.GCM.do_push/3>
    Args: []`

**Comment by hpopp** [comment]
Fixed the error in 8f1932fcc3e50f37fad23af00aa990aaa809b752. Turns out `String.to_existing_atom` doesn't want to play nice on the GCM side. I can't publish a new hex release until I've resolved the chatterbox github dependency, but in the meantime you can point your mix file to this repo.

**Comment by hpopp** [comment]
Fix now available on hex under v0.10.0
