### ISSUE TITLE
Crash when pushing to APNS

### ISSUE THREAD

**Issue by mdillavou** [codedge-llc/pigeon#36]
I am running pigeon 0.9.0, and occasionally see the following error message. When this happens, the push notification fails to send. It appears as though the process is restarted correctly, and the next time, the notification is sent correctly.

```
/var/log/galdr/system.log prod-us-galdr-20 13:51:57.577 [error] GenServer :apns_worker terminating
/var/log/galdr/system.log prod-us-galdr-20 ** (stop) exited in: :gen_fsm.sync_send_all_state_event(#PID<0.24316.21>, {:new_stream, #PID<0.24310.21>})
    ** (EXIT) no process
    (stdlib) gen_fsm.erl:249: :gen_fsm.sync_send_all_state_event/2
    (chatterbox) src/h2_client.erl:128: :h2_client.send_request/3
    (pigeon) lib/pigeon/apns_worker.ex:108: Pigeon.APNSWorker.send_push/3
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by hpopp** [comment]
Might be an issue with chatterbox. I'm currently in the process of migrating to a new HTTP/2 client, which should hopefully be out sometime this week.

**Comment by mdillavou** [comment]
Just out of curiosity, what are you considering as a replacement for chatterbox?

**Comment by hpopp** [comment]
Pigeon used custom HTTP/2 code before migrating to chatterbox, which I'm repurposing into a new hex package called [kadabra](https://github.com/codedge-llc/kadabra). I already have it working with pigeon, just no dynamic header table yet (apns-id's are incrementally indexed).
