### ISSUE TITLE
apns_worker seems to randomly hang at startup

### ISSUE THREAD

**Issue by seenickcode** [codedge-llc/pigeon#4]
Hello, I wanted to ask if anyone could recommend a way to troubleshoot this:

````
09:59:33.175 [debug] Starting apns_worker
         mode: dev, cert: cert.pem, key: key.pem
```

I'm getting this on my local machine randomly for pigeon 0.5.1 whereas I never used to see this message in the same version.

It seems to be trying to get a connection with apns but what could be causing this?

Thanks,

**Comment by hpopp** [comment]
That message prints when it finds a valid config and sets up a connection. Are you intending to start the APNS worker or is it somehow starting itself?

**Comment by maxmouchet** [comment]
I have the same issue since a few days with Phoenix.
This message shows up, the server is frozen, and eventually timeout : 
```
Kernel pid terminated (application_controller) ({application_start_failure,pigeon,{{shutdown,{failed_to_start_child,apns_worker,{{badmatch,{error,etimedout}},[{'Elixir.Pigeon.APNSWorker',init,1, [...]
```

It seems to appears randomly.

**Comment by hpopp** [comment]
I was able to recreate this bug sporadically. There isn't a timeout set in the `:ssl.connect` call, so when it fails, everything locks up. Best fix I can think of is to retry the connection twice more before failing with a timeout error. So far it seems handle it pretty well.

**Comment by hpopp** [comment]
Something else I just realized: when the `:dev`/`:prod` mode config doesn't match the certificate used, Apple ignores the connection and this issue also occurs.
