### ISSUE TITLE
Interested in supporting `Apple Push Notification Authentication Key`...

### ISSUE THREAD

**Issue by zepplock** [codedge-llc/pigeon#41]
which is JWT per organization instead of per app certificate?

**Comment by hpopp** [comment]
Yes it's on my list, once #40 is published. It will play nicely with the new configuration style.

**Comment by yepesasecas** [comment]
Any update here ? 
Apple Push Notification Authentication Key supported? 
How can I help,

regards

**Comment by hpopp** [comment]
I'll take a look at this. If it's not terribly difficult I'll slip it in with the next major release.

**Comment by hpopp** [comment]
Now available in `v1.2.0`. Closing this.
