### ISSUE TITLE
Hpack error when sending more than 599 notifications using same APNSWorker

### ISSUE THREAD

**Issue by Damirados** [codedge-llc/pigeon#44]
```
17:05:51.191 [error] GenServer #PID<0.240.0> terminating
** (ArgumentError) argument error
    :erlang.byte_size(3420729)
    (kadabra) lib/hpack/table.ex:108: Kadabra.Hpack.Table.entry_size/1
    (kadabra) lib/hpack/table.ex:82: Kadabra.Hpack.Table.add_header/2
    (kadabra) lib/hpack.ex:67: Kadabra.Hpack.literal_header_inc_indexing/2
    (kadabra) lib/hpack.ex:17: Kadabra.Hpack.do_decode_headers/3
    (kadabra) lib/connection.ex:146: Kadabra.Connection.do_recv_headers/2
    (kadabra) lib/connection.ex:80: Kadabra.Connection.handle_cast/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
```

It's obviously kadabra issue but i'm posting it here because it's easly reproducible using pigeon.

To reproduce this. Send 599 notifcations using same APNSWorker (my topic length is 20, don't know if makes any difference). Try sending another one.

**Comment by hpopp** [comment]
I'll take a look at this today. I had a feeling something like this would crop up.

**Comment by hpopp** [comment]
Found it! Crash happens from a bad parse on a `429` status code, which usually indicates a `too_many_requests` error. I'll have it patched shortly.

As far as I know this error only happens when you send to the same device token repeatedly. Are you sending to the same device?

**Comment by akositi** [comment]
Yes I was sending to one device. Sorry forgot to mention that.

Thanks for patching.


This next part is not related to issue.

I had to modify APNSWorker code to fit it in my project. It's system that manages push notifications for many apps using same server so I decided to put APNSWorker under `:simple_one_for_one` supervisor and added `handle_call` to query for name, I also save time of last sent push notification in state and have worker terminate itself if it sits idle for too long. If you are interested in supporting that feature I would be happy to tidy it up a bit and make a PR.

**Comment by Damirados** [comment]
Yes I was sending to one device. Sorry forgot to mention that.

Thanks for patching.

This next part is not related to issue.

I had to modify APNSWorker code to fit it in my project. It's system that manages push notifications for many apps using same server so I decided to put APNSWorker under :simple_one_for_one supervisor and added handle_call to query for name, I also save time of last sent push notification in state and have worker terminate itself if it sits idle for too long. If you are interested in supporting that feature I would be happy to tidy it up a bit and make a PR.

**Comment by hpopp** [comment]
I'm a little confused, pigeon already supports multiple configured sockets plus the ability to start/stop new ones.

**Comment by Damirados** [comment]
You are right. In theory I could have written my system using `APNS.start_connection/2` and `APS.stop_connection/1` but it would have made code on my side more complex.

Basically what I have now is app (which is trimed down verions of pigeon) with this api `APNSD.push(notifications, cert)` (D stands for dynamic). Where `cert` is string which contains certificate and private key `[{:Cerficate, cert, _}, {:PrivateKeyInfo, key, _}] = public_key.pem_decode(cert)`. 

And when you call that line APNSD checks if there is worker with opened connection using that `cert`, starts one if there isn't and sends notifications using it. Worker terminates itself if it sits idle for more than one hour.

I'll publish it as pigeon fork with extra module some time tommorow so you can see if it makes sense for pigeon to support something like that.

**Comment by Damirados** [comment]
Here are changes that I made to make Pigeon more useful to my project: https://github.com/entropiahr/pigeon

Quick sum:
  - APNSWorker has last_activity in state if dynamic flag set will check every hour and terminate if passed
  - APNSD module wraps worker for my specific use (should be worked more on and put in APNS)

  - GCM supports same api as APNSD with sync return of group `%{ok: list, error: map}` notifications (you should probably standardize api across all platforms)
  - GCM with new api groups notifications and optimizes things behind scenes

Changes are really ready for PR but may still help you. If you are going to support APNS with JWT you will need something similar to APNSD.

This issue should be closed.

**Comment by Damirados** [comment]
Sorry I meant nor really ready for PR.

**Comment by hpopp** [comment]
I'll definitely refer back to this code moving forward. Much thanks!
