### ISSUE TITLE
Running multiple instances of the same APNS worker

### ISSUE THREAD

**Issue by asgoel** [codedge-llc/pigeon#46]
Is there a way to run multiple instances of the same APNS worker (for example, using poolboy)? Would be helpful to be able to open up multiple connections for the same key/cert and parallelize notification sending in that regard.

**Comment by hpopp** [comment]
Connections can be started and stopped dynamically. For example, if you wanted to spin one up just for a few pushes.

```elixir
# Starting a connection called :worker_1
Pigeon.APNS.start_connection(:worker_1, mode: :dev, cert: System.get_env("APNS_CERT"), key: System.get_env("APNS_CERT_KEY"))

n = Pigeon.APNS.Notification.new("token", "msg")
Pigeon.APNS.push(n, to: :worker_1)

# Stopping
Pigeon.APNS.stop_connection(:worker_1)
```

Custom connections can also be setup in the config, exactly like `:default`.

If you wanted to keep it purely synchronous, I would spin up a simple GenServer that could round-robin several connections started like the example above. Depending on your use case, you may find it easier to just pass an `on_response` callback into `APNS.push/3` and fire off as many at will. Pigeon's internals are completely asynchronous. The sync push API exists purely for convenience.

**Comment by asgoel** [comment]
I see, didn't know about manually starting connections. In the latter case, there is still only one worker per connection right? So even if the push call is asynchronous, the calls to APNs would not be because they're all going through a single worker. I guess I wanted an asynchronous way to send messages with multiple connections, to really speed it up.

**Comment by hpopp** [comment]
Despite being one connection, HTTP/2 is far better than traditional HTTP for spamming a bunch of data over the wire. The current implementation is already ridiculously fast, but I see your point. In the future I'll likely implement some sort of autoscaling behavior. It'll require some proper benchmarking to figure out a reasonable default number of connections.

**Comment by maarek** [comment]
In your example above, I believe `Pigeon.APNS.push(n, to: :worker_1)` should be `Pigeon.APNS.push(n, name: :worker_1)`

**Comment by hpopp** [comment]
It should, that was a typo on my part. The option will be changing to `to` in future releases.

**Comment by hpopp** [comment]
Closing now that #57 is merged
