### ISSUE TITLE
Dynamic Configurations

### ISSUE THREAD

**Issue by maarek** [codedge-llc/pigeon#49]
Would you recommend using Pigeon.XXX.start_connection in order to dynamically load the certs/keys instead of hard coding them into the config? A worker would be started before a batch push and then finished upon response so that we can guarantee it's not lingering when not needed.

Thoughts?

**Comment by hpopp** [comment]
From the [APNS docs](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW1)
> Keep your connections with APNs open across multiple notifications; do not repeatedly open and close connections. APNs treats rapid connection and disconnection as a denial-of-service attack. You should leave a connection open unless you know it will be idle for an extended period of time—for example, if you only send notifications to your users once a day, it is acceptable practice to use a new connection each day.

It really depends on your use case. HTTP/2 connections are expensive to set up, but lightweight once established.

**Comment by idyll** [comment]
I am interested in dynamically adding certs and projects -- we have several iOS apps and would like to just push from a centralized point.

Dynamic config is super interesting to me too. It'd be cool if we didn't have to push a new server build to add a new project.

**Comment by hpopp** [comment]
I'm a little confused. Is `APNS.start_connection` not sufficient for dynamic configs?

**Comment by idyll** [comment]
Maybe it's me that's confused. I thought you were suggesting against that usage case...

**Comment by hpopp** [comment]
It really depends on how often the connection is going to be used. I wouldn't recommend opening a new connection per batch unless the batch happens infrequently. (e.g., I wouldn't open a new connection just to notify all users of a new comment on a post)

If you need dynamic configs, you have no choice but to use `start_connection`. In that case, I would probably write a service that keeps the connection open and kills it after a certain period of inactivity.

**Comment by idyll** [comment]
Once configured we'd need them open indefinitely. We'd want to reopen them if they closed.
This isn't so much "send a batch" but more dynamically loading certs.

**Comment by hpopp** [comment]
Sounds like something beyond the scope of pigeon. It shouldn't be storing connection configuration outside of a mix config.

If you're centralizing this into a service, I would write one that persists these configs in a db or `dets` and have your various apps "register" with the service as needed, starting the appropriate APNS connections.

**Comment by maarek** [comment]
I was looking at using the new process Registry to manage Pigeon connections. Start them and register them if they aren't available and use the currently registered one if they are.

**Comment by idyll** [comment]
I will check into that. Thanks for the tip. If this works for me I will make a PR for the readme or start a wiki page on suggestions to implement this.

**Comment by maarek** [comment]
@idyll Any luck on your end? My project got pushed to the side but was running into some problems because start_connection requires a name which is an atom. I don't necessarily want to dynamically create atoms in order to add a name to each of these workers but would prefer to have a worker start and just return a PID that I can store and recall when needed from a process registry.

**Comment by idyll** [comment]
I was sidetracked, but I am actually looking into it again this coming week so I will update you.

**Comment by hpopp** [comment]
Rewrote `start_connection/1` to allow dynamic connections (#57). 

Note: when pushing, the `name` option has been renamed to `to`.

Sample usage:
```elixir
{:ok, pid} = Pigeon.APNS.start_connection(cert: "cert.pem", key: "key.pem", mode: :dev)
Pigeon.APNS.push(notif, to: pid)

{:ok, pid2} = Pigeon.APNS.start_connection(cert: "cert.pem", key: "key.pem", mode: :dev, name: :custom)
Pigeon.APNS.push(notif, to: :custom)

{:ok, pid3} = Pigeon.APNS.start_connection(:test) # Creates from config file under key :test
```

Connections loaded from the config file are supervised by pigeon itself. Everything else is not. This should play along just fine with a registry though I haven't specifically tested it yet.

**Comment by maarek** [comment]
Looks good!

**Comment by callmeahab** [comment]
Sorry to reopen this, but is there a way to have multiple configurations for GCM too?

**Comment by hpopp** [comment]
GCM keys can be configured on a per-push basis.

```elixir
Pigeon.GCM.push(notification, %{gcm_key: gcm_key})
```

Not very well documented, but this is going to be redone once the new FCM implementation is finished.

**Comment by callmeahab** [comment]
Thanks, I was trying with `%{key: "AIzaSyAe-......"}`.
