### ISSUE TITLE
Is using JWT with pigeon possible?

### ISSUE THREAD

**Issue by shawnbro** [codedge-llc/pigeon#50]
Trying to set up Push in our app using the functionality outlined here:

http://stackoverflow.com/questions/39671902/apple-push-notification-authentication-key-sandbox-production

Is it possible to use Pigeon with Json web tokens?

**Comment by hpopp** [comment]
Not yet, but it's on the list to be eventually implemented.

**Comment by hpopp** [comment]
Now available in `v1.2.0`
