### ISSUE TITLE
v1.0

### ISSUE THREAD

**Issue by hpopp** [codedge-llc/pigeon#54]
Opening this for a general discussion on tasks remaining for `v1.0` release.

*Task list so far...*
- [x] Finish docs and doctests #53 
  - [x] Update the push guides
- [x] FCM #52 
  - [x] Custom response struct
  - [x] Handling over 1000 reg IDs
  - [ ] Custom worker configurations
  - [x] Priority Option #51 
- [x] ADM
  - [ ] Synchronous pushing
  - [x] Custom worker configs
- [ ] APNS
  - [ ] Custom response struct for synchronous pushes (and maybe async too?)
  - [x] Make workers not require an atom name
  - [ ] Logging disable option for callbacks

I'm not sure yet what kind of API ADM pushing would look like. Despite being Android, its implementation looks a lot more like APNS.

**Comment by talklittle** [comment]
What would "synchronous push" entail? Are you thinking something more involved than implementing `GenServer.handle_call/3` and then wrapping `GenServer.call/3` with a public API function?

**Comment by hpopp** [comment]
The current APNS implementation still uses `handle_cast` but waits on the task(s) and returns the result. The old API took `on_response` as a parameter. Now pushes are synchronous by default, and async only in the presence of an `on_response` options key.

```elixir
  # /lib/pigeon/apns.ex

  def push(notification, opts \\ [])
  def push(notification, opts) when is_list(notification) do
    case opts[:on_response] do
      nil ->
        tasks = for n <- notification, do: Task.async(fn -> do_sync_push(n, opts) end)
        tasks
        |> Task.yield_many(@default_timeout + 500)
        |> Enum.map(fn {task, response} -> response || Task.shutdown(task, :brutal_kill) end)
        |> group_responses
      on_response -> push(notification, on_response, opts)
    end
  end
  def push(notification, opts) do
    case opts[:on_response] do
      nil -> do_sync_push(notification, opts)
      on_response -> push(notification, on_response, opts)
    end
  end

  defp do_sync_push(notification, opts) do
    pid = self()
    on_response = fn(x) -> send pid, {:ok, x} end

    worker_name = opts[:name] || Config.default_name
    GenServer.cast(worker_name, {:push, :apns, notification, on_response})

    receive do
      {:ok, x} -> x
    after
      @default_timeout -> {:error, :timeout, notification}
    end
  end
```

**Comment by maarek** [comment]
How about adding some debug logging? If the callback doesn't fire you then have to resort to using the debugger to figure out what went wrong.
