### ISSUE TITLE
Handle HTTPoison.Error

### ISSUE THREAD

**Issue by mkaszubowski** [codedge-llc/pigeon#59]
Currently, pigeon does not handle `HTTPoison.Error` when doing request to GCM (https://github.com/codedge-llc/pigeon/blob/master/lib/pigeon/gcm.ex#L52). This causes the process to crash if GCM is closing connection. After the max restart limit is reached, pigeon is causing the entire node to crash. 

A fragment of the crash report:

```=CRASH REPORT==== 1-Mar-2017::02:23:13 ===
  crasher:
    initial call: Elixir.Pigeon.GCM:-do_push/3-fun-2-/0
    pid: <0.1388.3>
    registered_name: []
    exception exit: {{badmatch,
                         {error,
                             #{'__exception__' => true,
                               '__struct__' => 'Elixir.HTTPoison.Error',
                               id => nil,
                               reason => closed}}},
                     [{'Elixir.Pigeon.GCM','-do_push/3-fun-1-',4,
                          [{file,"lib/pigeon/gcm.ex"},{line,52}]},
                      {'Elixir.Task.Supervised',do_apply,2,
                          [{file,"lib/task/supervised.ex"},{line,85}]},
                      {'Elixir.Task.Supervised',reply,5,
                          [{file,"lib/task/supervised.ex"},{line,36}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,240}]}]}
      in function  'Elixir.Task.Supervised':exit/4 (lib/task/supervised.ex, line 116)
      in call from 'Elixir.Task.Supervised':reply/5 (lib/task/supervised.ex, line 36)
```

I'm happy to help with the issue, but I'd appreciate any guidance on that. I'm not sure what's the best way to handle this error. I guess doing the request in the `case` statement and pattern matching on success and error would help, but maybe you can provide some feedback.

Or will be resolved by https://github.com/codedge-llc/pigeon/pull/52 ?

**Comment by hpopp** [comment]
Yes, all of the GCM libs have been completely rewritten. I'll make a note to check in testing before release.

**Comment by mkaszubowski** [comment]
Sure, that's great! Do you have any estimates on the release date of the new GCM code?

**Comment by hpopp** [comment]
Closing because no longer relevant with FCM http/2 support
