### ISSUE TITLE
Heroku crash

### ISSUE THREAD

**Issue by jeandavid** [codedge-llc/pigeon#65]
I am the 0.11.0 version. The crashed happened suddenly: the app has been running for at a month before previous update. 
Any help? 

![heroku_crash_log](https://cloud.githubusercontent.com/assets/3328783/24200588/38fac7b0-0f16-11e7-86a2-f9cf3d2c9028.jpg)

**Comment by hpopp** [comment]
Was your connection specified in the config or did you start one manually?

**Comment by jeandavid** [comment]
Indeed it was a probably a bad cert/key. Disabling apns prevents the crash...Thanks!
