### ISSUE TITLE
Keeping APNS certs secret

### ISSUE THREAD

**Issue by zhumo** [codedge-llc/pigeon#7]
I see the discussion on #6 on how Pigeon is configured to look for the cert at a path relative to the root. For purposes of keeping various sensitive keys secret, I'm used to keeping them in the environment variables and out of source control. Is there a way to do this with APNS's certificate files? I'm using Heroku.

Thanks!

**Comment by hpopp** [comment]
At the moment that's not supported, but it's been on my list. I'll make it a priority for the next release. Something along the lines of modifying the same `apns_cert` and `apns_key` configs to optionally either be the full text of the cert or just a file path.

In the meantime perhaps there might be a way to encrypt your certificate before checking into source control? I haven't ever hosted with Heroku, but I'm thinking something along the lines of Travis CI,  decrypting the file before compiling and running the unit tests.

**Comment by zhumo** [comment]
Thanks!
