### ISSUE TITLE
Read keys/certificates at runtime

### ISSUE THREAD

**Issue by CrowdHailer** [codedge-llc/pigeon#74]
Is there any way to configure pidgeon to read configuration from the system at runtime?

something like the following. similar to how phoenix runtime configuration is setup.

```elixir
config :pigeon, :apns,
  default: %{
    cert: {:system, "APNS_CERTIFICATE"},
    key:  {:system, "APNS_KEY"},
    mode: :dev
}
```

**Comment by hpopp** [comment]
```
config :pigeon, :apns,
  default: %{
    cert: System.get_env("APNS_CERTIFICATE"),
    key:  System.get_env("APNS_KEY"),
    mode: :dev
}
```

I'll consider adding that as a convention. It already supports `{:your_app, "file.pem"}` for files relative to your app's `priv/` directory.

**Comment by CrowdHailer** [comment]
That solution you have suggested above will not work. `config.exs` is evaluated at compile time, so will only read the environment variables present on the development machine.

The second option you mentioned requires the keys to be added to source control, also not what we want.

**Comment by hpopp** [comment]
Workers can be started manually, however you want to configure them.

```elixir
{:ok, pid} = Pigeon.APNS.start_connection(cert: System.get_env("APNS_CERTIFICATE"), key: System.get_env("APNS_KEY"), mode: :dev)
Pigeon.APNS.push(notif, to: pid)

Pigeon.APNS.start_connection(cert: System.get_env("APNS_CERTIFICATE"), key: System.get_env("APNS_KEY"), mode: :dev, name: :custom)
Pigeon.APNS.push(notif, to: :custom)
```

**Comment by CrowdHailer** [comment]
That would be a workable solution for the moment. Thank you.

I would still like to see the `{:system, "ENV_NAME"}` in time. I think it is a nice convention

**Comment by CrowdHailer** [comment]
That would be a workable solution for the moment. Thank you.

I would still like to see the `{:system, "ENV_NAME"}` in time. I think it is a nice convention

**Comment by jdl** [comment]
Would it be possible to have a `Pigeon.GCM.start_connection` that takes the config like in your APNS example above? I suppose there would also have to be the `to:` option on `push` as well. 

Looking though the code, I don't see where `Pigeon.GCM.start_connection` is called at all, so maybe that's old code, or I'm missing something?

**Comment by hpopp** [comment]
The current version on master is a `v1.0` WIP that includes FCM http2 worker connections. I had planned to get it finished last week but some things came up. Refer to the `v0.13` branch for the current version on hex.

**Comment by jdl** [comment]
Oh, well I feel dumb now. I didn't even notice the branch. I tried passing in the `gcm_key` to `push` and it worked just fine. 

Thanks!

**Comment by hpopp** [comment]
So after doing some research, I'm considering using [this approach](https://elixirforum.com/t/what-is-the-difference-between-using-system-port-and-system-get-env-port-in-deployment/1975/12?u=hpopp) instead of `{:system, var}`, which is to be deprecated in phoenix.

Thoughts?

**Comment by talklittle** [comment]
@hpopp Do you mean adding a new overrideable `init/2` as in https://github.com/phoenixframework/phoenix/commit/ab4cd048c4bdfbd4185237401fcc9ead9f5bbf2b ? (which was added May, whereas the linked discussion was March) -- It's a really long debate so I wasn't sure which exact solution you were leaning toward. The original proposal was an `:on_init` option passing in `{Module, Function, Args}` but the commit I linked appears to have done away with that.

So when using Pigeon, if loading from System env (or wherever) at runtime is desired, then we would provide a module implementing the `init/2` callback?

If so, :+1: from me because that looks like the most flexible approach. Unfortunately comes with a lot of boilerplate, but I guess there's not a known superior solution right now.

**Comment by hpopp** [comment]
I like the tuple approach best, but not with an `:on_init` key or third argument. Something like

```elixir
config :pigeon, :apns,
  old_style_worker: %{
    cert: "cert.pem",
    key: "key_unencrypted.pem",
    mode: :dev
    use_2197: true
  },
  new_style_worker: {YourApp.Pigeon, :prod_config}
```

Where `YourApp.Pigeon.prod_config` would return a special config struct corresponding to the worker. This would allow you to group similar configs under one module.

Also in theory, you could use it to infer the type of worker, and potentially no longer need to group configs by `:apns`/`:fcm`/`:adm`.

I could see a future config looking something like

```elixir
config :pigeon, workers: [
  apns_default: {YourApp.Pigeon, :apns_dev_config},
  fcm_default: {YourApp.Pigeon, :fcm_config},
  adm_default: {YourApp.Pigeon, :adm_config}
]

**Comment by talklittle** [comment]
Thanks for the illustration. I think that is better because it's more flexible. Just sad that the elegant Mix config file doesn't work great with deployment workflows.
