### ISSUE TITLE
Error in "Custom Worker Connection" documentation

### ISSUE THREAD

**Issue by guidotripaldi** [codedge-llc/pigeon#76]
in [APNS (Apple iOS)](https://hexdocs.pm/pigeon/apns-apple-ios.html#content) documentation there is an error in the section _Custom Worker Connection_, as it states to use `to:` instead of `name:` as the option parameter for `Pigeon.APNS.push/2`

Instead of:

> Send pushes with a `to` option in your second parameter.
> 
>   n = Pigeon.APNS.Notification.new("your message", "your device token", "your push topic")
>   Pigeon.APNS.push(n, to: :custom_worker)
> 

should be:

> Send pushes with a `name` option in your second parameter.
> 
>   n = Pigeon.APNS.Notification.new("your message", "your device token", "your push topic")
>   Pigeon.APNS.push(n, name: :custom_worker)
>

**Comment by hpopp** [comment]
Which version are you using? `:name` was renamed to `:to`

**Comment by guidotripaldi** [comment]
My fault, I discover now that in my mix.ex file I still have `{:pigeon, "~> 0.10.0"}`
