### ISSUE TITLE
Firebase support

### ISSUE THREAD

**Issue by AaronVasquez** [codedge-llc/pigeon#77]
Hello, since FCM has replaced GCM, I was wondering if this library supports FCM?

**Comment by hpopp** [comment]
Current releases do support FCM-- just insert your API key. It'll be strongly recommended to only use FCM for major releases going forward (`v1.0+`). GCM support will remain on the `v0.13` branch.

**Comment by rkmax** [comment]
@hpopp could you please provide some example of setup using FCM because I did this

```
# config/dev.secret.exs
use Mix.Config

config :pigeon, :gcm,
  key: "server token grabbed from firebase console"
```

later in my code I did this
```
id = "token grabbed from my phone after register on FCM"
message = "Hello from here"
data = %{"type" => "sample" } # just dummy extra data
Pigeon.GCM.Notification.new(id, message, data) |> Pigeon.GCM.push fn(x) -> IO.inspect(x) end
```

the console show me the following
```
{:error, :authentication_error,
 %Pigeon.GCM.Notification{message_id: nil,
  payload: %{"data" => %{"type" => "sample"},
    "notification" => "Hello fom here"},
  registration_id: "token grabbed from my phone after register on FCM",
  updated_registration_id: nil}}
```

So it's possible I'm doing something wrong, I'm new to elixir so dont have a clue

**Comment by hpopp** [comment]
Have you verified your FCM key first in a shell?

```bash
# api_key=YOUR_SERVER_KEY

# curl --header "Authorization: key=$api_key" \
       --header Content-Type:"application/json" \
       https://fcm.googleapis.com/fcm/send \
       -d "{\"registration_ids\":[\"ABC\"]}"
```

**Comment by rkmax** [comment]
@hpopp my apologies I found the issue. I forget a `import_config "env.secret.exs"` :sweat_smile: .the library is working 100% really good for APNS and FCM :)
