### ISSUE TITLE
GOAWAY invalid_new_stream_id

### ISSUE THREAD

**Issue by asgoel** [codedge-llc/pigeon#84]
Seeing this issue on the new FCM update:
`Got GOAWAY, PROTOCOL_ERROR, Last Stream: 47, Rest: invalid_new_stream_id`.
Any ideas?

**Comment by hpopp** [comment]
Client connections must use odd-numbered stream IDs. Try checking the state of the workers and see if there are any even-numbered streams on the queue?

**Comment by asgoel** [comment]
Had to re-deploy, will check next time I see the errors

**Comment by asgoel** [comment]
turns out this is almost impossible to debug as the genservers keep restarting due to #83 so I can't actually grab the state of any worker, and this only happens under a lot of load. Let me know if there's another way to debug

**Comment by hpopp** [comment]
Try chunking your regIDs into no more than 100 or so per notification.

**Comment by asgoel** [comment]
Unfortunately due to application level semantics the notification payload is different for each token thus I'm not able to chunk the regIDs. The only reason I can think of for this happening that's not normal is that often these messages are sent out in huge batches (could be in the hundred thousands, chunked in groups of 10k). Would this be an issue?

**Comment by hpopp** [comment]
So after some digging I think I've found the problem. Large batches trigger the occasional `RST_STREAM, REFUSED_STREAM`, which Kadabra `v0.2` will return immediately without any headers or body set. These are likely getting thrown by exceeding the `max_concurrent_streams` on the connection, which I believe is around 100 or so. Quickest temporary fix would likely be to chunk in batches of 100 and stagger them by just a little.

I'm going to need to implement better `RST_STREAM` error handling and some sort of proper queueing. Some of this was already addressed in Kadabra `v0.3`, but the release isn't quite ready yet (and will bump min requirements to Elixir 1.4/OTP 19)

**Comment by hpopp** [comment]
Theoretically this could happen on APNS as well, though I'm surprised nobody has raised an issue yet.

**Comment by hpopp** [comment]
Pretty sure this is now fixed with #86. Published a `v1.0.3` release that needs Kadabra `v0.2.2`.

Let me know if the issue still persists. I was able to send 10,000 unique pushes in a single go.

**Comment by asgoel** [comment]
Ok, will give it a shot. I also moved to a genstage approach to be able to throttle the number of concurrent connections, so we'll see if the combination of that plus the new release works.
