### ISSUE TITLE
Adapters

### ISSUE THREAD

**Issue by CrowdHailer** [codedge-llc/pigeon#87]
It looks like you have removed the option of using chatterbox from the README. Are you moving away from a choice of adapters? 

I just released my version of an HTTP/2 client and was thinking of writing a version of pigeon that used it https://hexdocs.pm/ace/Ace.HTTP2.Client.html

**Comment by CrowdHailer** [comment]
I look forward to the guide
what phoenix adapters are you referring too

**Comment by hpopp** [comment]
https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint/cowboy_handler.ex

Phoenix's cowboy dependency is optional, meaning you can swap in whatever webserver you wish so long as you have an adapter for it.

**Comment by CrowdHailer** [comment]
Is that not the only adapter and it is maintained in the phoenix repo and by the phoenix team?

**Comment by hpopp** [comment]
As far as I know, yes, but anyone should be able to write one, unless that's changed.

**Comment by CrowdHailer** [comment]
this probably isnt the place but why does phoenix have a cowboy handler? isnt plug meant to abstract that away

**Comment by hpopp** [comment]
I've written a simple adapter guide under `Pigeon.Http2.Client` on #89. Is there anything that should be better clarified?

**Comment by hpopp** [comment]
Closing now that `v1.1.0` is out
