### ISSUE TITLE
GOAWAY, ENHANCE_YOUR_CALM, too_many_pings

### ISSUE THREAD

**Issue by talklittle** [codedge-llc/pigeon#92]
With Pigeon 1.0.3 and FCM, about every ~129 seconds I'm seeing 

    [error] Got GOAWAY, ENHANCE_YOUR_CALM, Last Stream: 727, Rest: too_many_pings

But also when it wraps around(?) to `Last Stream: 1` which appears in error logs just a few seconds after the previous "GOAWAY" error message.

I'm not sure why the ping error would come every 129 seconds when the default ping period is [600 seconds](https://github.com/codedge-llc/pigeon/blob/a7ad6cc4d5327a84199d1010f26c22f660902f6b/lib/pigeon/fcm/worker.ex#L10). I can probably make it go away by configuring the ping period, but just wondering if anyone knows why this happens?

**Comment by hpopp** [comment]
`GOAWAY` closes the connection, so the stream ID will reset to `1`.

A new ping is scheduled every time a worker's socket reconnects, so if I had to guess, FCM is closing the socket every 129 seconds. It's probably scheduling way too many pings.

I'll need to update the `Configurable` protocol in v1.1 to disable pings for FCM entirely.

**Comment by hpopp** [comment]
Closing because this should now be fixed. Also made corresponding fix on the v1.1.0 branch.
