### ISSUE TITLE
GOAWAY, FRAME_SIZE_ERROR, Rest: framer_error

### ISSUE THREAD

**Issue by talklittle** [codedge-llc/pigeon#95]
[error] Got GOAWAY, FRAME_SIZE_ERROR, Last Stream: 239, Rest: framer_error

First time seeing this, ~~a single time only so far. Maybe a fluke from recent server restart.~~

Pigeon 1.1.0-rc.0 + PR #94 (probably unrelated to this)
Kadabra 0.3.1

**EDIT:** Got it again, 20 minutes + 1 second after previous one.

**EDIT 2:** Definitely has something to do with the specific data I'm sending, or the tokens I'm attempting to send to. Will investigate more.

**EDIT 3:** Happens when sending one FCM Notification to 199 regIDs. Other notifications have a lot fewer regIDs and don't trigger the error. I'll try chunking to groups of 100 regIDs for now. [EDIT: This successfully worked around the issue.]

**Comment by hpopp** [comment]
It's probably something on Kadabra's end, though `FRAME_SIZE_ERROR` can mean several different things. I'll see if I can recreate.

**Comment by hpopp** [comment]
It was definitely a kadabra issue. Fixed with https://github.com/codedge-llc/kadabra/pull/19. After some minor cleanup I'll publish a `v0.3.2` release.

**Comment by hpopp** [comment]
`v1.1.0-rc.1` has been posted with updated kadabra, closing this.
