### ISSUE TITLE
Add testing service that would catch all sent messages and store them in way that would allow to check if notification was really sent

### ISSUE THREAD

**Issue by hauleth** [codedge-llc/pigeon#96]
Something like [Bamboo's `TestAdapter`](https://github.com/thoughtbot/bamboo#adapters).

**Comment by hpopp** [comment]
Pigeon already stores the response on the notification itself, unless you're referring to something that would process the pushes but not actually send them.

I know FCM has a `dry_run` option for doing just that. I'll look into options for APNS/ADM.

**Comment by alexandru-calinoiu** [comment]
I think the idea is to simply make this easy to use when writing unit tests.

**Comment by alexandru-calinoiu** [comment]
Actually looking over the merged pr's I think this https://github.com/codedge-llc/pigeon/pull/199 solves the problem and this issue can be clossed.

**Comment by hpopp** [comment]
Yup, it was one of the big things added with Pigeon 2.0. The `dry_run` options are still available if you want to test with valid creds, but the sandbox adapter maxes local dev and tests super easy.
